server:
  port: 8081
  servlet:
    context-path: /
#  ssl:
#    enabled: true
#    key-store: conf/certificate.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-password: 123456
#
flashphoner:
# you can put here any wcs settings (flashphoner.properties)
  wcs:
    disable_rest_requests: true
#    rels_client_type: file
#    rels_enabled: MEDIA_SESSION,RTMP_IN_BUFFER,RTMP_OUT_BUFFER,RTP_SYNCHRONIZATION,HLS_SEGMENTER,HLS_STREAM
  zapp:
    ip: ${ZAPP_SERVER_IP}
    ip_local: ${ZAPP_SERVER_IP}
    storage-type: MONGO
    mongo-storage-database: zapp_alpha_test
    mongo-storage-url: "mongodb://admin:Abcd1111@${MONGO_IP}:27017/?w=majority&authSource=admin"
#  cdn:
#    enabled: false
#    ip: 192.168.0.1
#    resolve-ip: false
#    role: sfu_signaling
#    allowed-ips: 192.168.0.0/24
#
#
#logging:
#  level:
#    root: warn